## 1- Dataset & EDA

In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [91]:
df=pd.read_csv(r"C:\Users\hp\Downloads\hotel_bookings.csv")
df_backup=df.copy()

In [92]:
print(df.shape)

(600000, 42)

In [93]:
df.head()

,Unnamed: 0,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,...,length_of_stay_days,is_domestic_booking,hotel_booking_count,city_booking_count,Date,Year,Month,Month name,Day,Day name
0,41,42,57,Ocean Boutique Hotel 57,Amsterdam,Netherlands,4,Double,Wei Yilmaz,wei.yilmaz42@hotmail.com,...,9.0,0,2439,26480,2024-01-22,2024,1,January,22,Monday
1,50,51,247,Sapphire Palace 247,Singapore,Singapore,4,Double,Maria Martinez,maria.martinez51@yahoo.com,...,9.0,0,2377,26191,2024-01-17,2024,1,January,17,Wednesday
2,173,174,138,Palm Suites 138,Cairo,Egypt,2,Double,Salma Bianchi,salma.bianchi174@hotmail.com,...,8.0,1,2439,9658,2024-01-03,2024,1,January,3,Wednesday
3,179,180,27,Grand Boutique Hotel 27,Paris,France,3,Twin,James Nassar,james.nassar180@hotmail.com,...,3.0,0,2416,21513,2024-01-23,2024,1,January,23,Tuesday
4,211,212,69,Royal Boutique Hotel 69,Sharm El Sheikh,Egypt,4,Single,Luca Kim,luca.kim212@gmail.com,...,1.0,1,2361,35839,2024-01-04,2024,1,January,4,Thursday

In [94]:
df.tail()

,Unnamed: 0,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,...,length_of_stay_days,is_domestic_booking,hotel_booking_count,city_booking_count,Date,Year,Month,Month name,Day,Day name
599995,599734,599735,103,Crown Towers 103,Amman,Jordan,5,Single,Zeynep Petrov,zeynep.petrov599735@icloud.com,...,10.0,0,2360,24055,2026-12-12,2026,12,December,12,Saturday
599996,599768,599769,195,Pearl Residence 195,Athens,Greece,2,Executive Suite,Rania Lee,rania.lee599769@outlook.com,...,6.0,0,2444,9641,2026-12-29,2026,12,December,29,Tuesday
599997,599868,599869,225,Grand Hotel 225,Kuala Lumpur,Malaysia,2,Single,Karim Youssef,karim.youssef599869@yahoo.com,...,2.0,0,2407,23951,2026-12-16,2026,12,December,16,Wednesday
599998,599915,599916,194,Ocean Palace 194,Istanbul,Turkey,3,Double,Elena Haddad,elena.haddad599916@icloud.com,...,8.0,0,2404,21640,2026-12-27,2026,12,December,27,Sunday
599999,599955,599956,147,Blue Resort & Spa 147,Alexandria,Egypt,4,Single,Sara Martinez,sara.martinez599956@gmail.com,...,13.0,1,2338,14386,2026-12-13,2026,12,December,13,Sunday

In [95]:
print("Info about columns and data types:")
df.info()

Info about columns and data types:
<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           600000 non-null  int64
 1   booking_id           600000 non-null  int64
 2   hotel_id             600000 non-null  int64
 3   hotel_name           600000 non-null  str
 4   city                 600000 non-null  str
 5   country              600000 non-null  str
 6   hotel_stars          600000 non-null  int64
 7   room_type            600000 non-null  str
 8   guest_name           600000 non-null  str
 9   guest_email          600000 non-null  str
 10  adults               600000 non-null  int64
 11  children             600000 non-null  int64
 12  checkin_date         600000 non-null  str
 13  checkout_date        600000 non-null  str
 14  nights               600000 non-null  int64
 15  booking_date         600000 non-null  str
 16  booking_channel      600000 non-null  str
 17  payment_method       600000 non-null  str
 18  price_per_night_usd  600000 non-null  float64
 19  total_price_usd      600000 non-null  float64
 20  booking_status       600000 non-null  str
 21  guest_rating         600000 non-null  float64
 22  special_requests     600000 non-null  str
 23  booking_month        600000 non-null  str
 24  nights_check         600000 non-null  int64
 25  is_cancelled         600000 non-null  str
 26  calculated_total     600000 non-null  float64
 27  ratio                600000 non-null  float64
 28  checkin_year         600000 non-null  int64
 29  checkin_month        600000 non-null  int64
 30  checkin_weekday      600000 non-null  str
 31  checkin_is_weekend   600000 non-null  int64
 32  length_of_stay_days  600000 non-null  float64
 33  is_domestic_booking  600000 non-null  int64
 34  hotel_booking_count  600000 non-null  int64
 35  city_booking_count   600000 non-null  int64
 36  Date                 600000 non-null  str
 37  Year                 600000 non-null  int64
 38  Month                600000 non-null  int64
 39  Month name           600000 non-null  str
 40  Day                  600000 non-null  int64
 41  Day name             600000 non-null  str
dtypes: float64(6), int64(17), str(19)
memory usage: 192.3 MB

In [96]:
print("Statistics for numeric columns:")
print(df.describe())

Statistics for numeric columns:

          Unnamed: 0     booking_id       hotel_id    hotel_stars  \
count  600000.000000  600000.000000  600000.000000  600000.000000
mean   299999.500000  300000.500000     125.456407       3.462128
std    173205.225094  173205.225094      72.141805       1.124806
min         0.000000       1.000000       1.000000       2.000000
25%    149999.750000  150000.750000      63.000000       2.000000
50%    299999.500000  300000.500000     126.000000       4.000000
75%    449999.250000  450000.250000     188.000000       4.000000
max    599999.000000  600000.000000     250.000000       5.000000

              adults       children         nights  price_per_night_usd  \
count  600000.000000  600000.000000  600000.000000        600000.000000
mean        2.499810       1.500790       7.501678           261.880537
std         1.119172       1.118458       4.026189           117.038976
min         1.000000       0.000000       1.000000            44.100000
25%         1.000000       1.000000       4.000000           171.630000
50%         2.000000       2.000000       7.000000           239.240000
75%         4.000000       3.000000      11.000000           333.050000
max         4.000000       3.000000      14.000000           575.180000

       total_price_usd   guest_rating  ...   checkin_year  checkin_month  \
count    600000.000000  600000.000000  ...  600000.000000  600000.000000
mean       1854.288842       2.996807  ...    2024.998680       6.514277
std        1324.682448       1.001218  ...       0.816345       3.444581
min          39.340000       1.000000  ...    2024.000000       1.000000
25%         809.190000       2.996807  ...    2024.000000       4.000000
50%        1555.380000       2.996807  ...    2025.000000       7.000000
75%        2598.960000       3.000000  ...    2026.000000      10.000000
max        5283.615000       5.000000  ...    2026.000000      12.000000

       checkin_is_weekend  length_of_stay_days  is_domestic_booking  \
count       600000.000000        600000.000000        600000.000000
mean             0.284958             7.501678             0.164285
std              0.451395             4.026189             0.370534
min              0.000000             1.000000             0.000000
25%              0.000000             4.000000             0.000000
50%              0.000000             7.000000             0.000000
75%              1.000000            11.000000             0.000000
max              1.000000            14.000000             1.000000

       hotel_booking_count  city_booking_count           Year          Month  \
count        600000.000000        600000.00000  600000.000000  600000.000000
mean           2400.887167         23751.53917    2024.998680       6.514277
std              46.262699          9715.67189       0.816345       3.444581
min            2264.000000          7216.00000    2024.000000       1.000000
25%            2368.000000         16779.00000    2024.000000       4.000000
50%            2399.000000         21809.00000    2025.000000       7.000000
75%            2428.000000         26191.00000    2026.000000      10.000000
max            2549.000000         45408.00000    2026.000000      12.000000

                 Day
count  600000.000000
mean       15.728490
std         8.792845
min         1.000000
25%         8.000000
50%        16.000000
75%        23.000000
max        31.000000

[8 rows x 23 columns]

In [97]:
print("Statistics for text/categorical columns:")
print(df.describe(include='object'))

Statistics for text/categorical columns:

C:\Users\hp\AppData\Local\Temp\ipykernel_6504\2035940989.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))

                    hotel_name    city country room_type           guest_name  \
count                   600000  600000  600000    600000               600000
unique                     250      30      22         7                 1187
top     Sunset Beach Resort 61  London   Egypt    Triple  William Abdelrahman
freq                      2549   45408   98571     86138                 1485

                     guest_email checkin_date checkout_date booking_date  \
count                     600000       600000        600000       600000
unique                    600000         1095          1108         1184
top     wei.yilmaz42@hotmail.com   2026-07-06    2025-04-29   2025-03-28
freq                           1          641           632          623

       booking_channel payment_method booking_status special_requests  \
count           600000         600000         600000           600000
unique               8              6              4               13
top        Booking.com    Credit Card      Completed       No Request
freq            168119         252067         300067           120304

       booking_month is_cancelled checkin_weekday        Date Month name  \
count         600000       600000          600000      600000     600000
unique            39            2               7        1095         12
top       2024-07-01    Confirmed          Monday  2026-07-06     August
freq           17293       479767           86462         641      51138

       Day name
count    600000
unique        7
top      Monday
freq      86462

In [98]:
print("Missing values in each column:")
df.isnull().sum()

Missing values in each column:

Unnamed: 0             0
booking_id             0
hotel_id               0
hotel_name             0
city                   0
country                0
hotel_stars            0
room_type              0
guest_name             0
guest_email            0
adults                 0
children               0
checkin_date           0
checkout_date          0
nights                 0
booking_date           0
booking_channel        0
payment_method         0
price_per_night_usd    0
total_price_usd        0
booking_status         0
guest_rating           0
special_requests       0
booking_month          0
nights_check           0
is_cancelled           0
calculated_total       0
ratio                  0
checkin_year           0
checkin_month          0
checkin_weekday        0
checkin_is_weekend     0
length_of_stay_days    0
is_domestic_booking    0
hotel_booking_count    0
city_booking_count     0
Date                   0
Year                   0
Month                  0
Month name             0
Day                    0
Day name               0
dtype: int64

In [99]:
print("Number of duplicate rows:")
df.duplicated().sum()

Number of duplicate rows:

np.int64(0)

In [100]:
avg_price_by_stars = df.groupby('hotel_stars')['total_price_usd'].mean()
print("\nAverage total price by hotel stars:")
print(avg_price_by_stars)

Average total price by hotel stars:
hotel_stars
2    1424.845729
3    1696.689094
4    2046.004115
5    2286.319315
Name: total_price_usd, dtype: float64

In [101]:
total_bookings = len(df)
print(total_bookings)

600000

In [102]:
status_percent = df['booking_status'].value_counts(normalize=True) * 100
print(status_percent)

booking_status
Completed    50.011167
Confirmed    29.950000
Cancelled    15.014333
No-Show       5.024500
Name: proportion, dtype: float64

In [103]:
avg_nights = df['nights'].mean()
print(f"Average nights per booking: {avg_nights:.2f}")

Average nights per booking: 7.50

In [104]:
avg_price = df['total_price_usd'].mean()
print(f"Average total price per booking: {avg_price:.2f} USD")

Average total price per booking: 1854.29 USD

In [105]:
most_common_room = df['room_type'].mode()[0]
print(f"Most common room type: {most_common_room}")

Most common room type: Triple

In [106]:
most_common_channel = df['booking_channel'].mode()[0]
print(f"Most common booking channel: {most_common_channel}")

Most common booking channel: Booking.com

## 2- Data Cleaning

In [107]:
print("Duplicate rows:", df.duplicated().sum())
print("Percentage:", round(df.duplicated().sum()/len(df)*100, 1))

Duplicate rows: 0
Percentage: 0.0

In [108]:
df.drop_duplicates(inplace=True)
print(df.shape)

(600000, 42)

In [109]:
print(df.isnull().sum())
print()
print(round(df.isnull().sum()/len(df)*100, 1))

Unnamed: 0             0
booking_id             0
hotel_id               0
hotel_name             0
city                   0
country                0
hotel_stars            0
room_type              0
guest_name             0
guest_email            0
adults                 0
children               0
checkin_date           0
checkout_date          0
nights                 0
booking_date           0
booking_channel        0
payment_method         0
price_per_night_usd    0
total_price_usd        0
booking_status         0
guest_rating           0
special_requests       0
booking_month          0
nights_check           0
is_cancelled           0
calculated_total       0
ratio                  0
checkin_year           0
checkin_month          0
checkin_weekday        0
checkin_is_weekend     0
length_of_stay_days    0
is_domestic_booking    0
hotel_booking_count    0
city_booking_count     0
Date                   0
Year                   0
Month                  0
Month name             0
Day                    0
Day name               0
dtype: int64

Unnamed: 0             0.0
booking_id             0.0
hotel_id               0.0
hotel_name             0.0
city                   0.0
country                0.0
hotel_stars            0.0
room_type              0.0
guest_name             0.0
guest_email            0.0
adults                 0.0
children               0.0
checkin_date           0.0
checkout_date          0.0
nights                 0.0
booking_date           0.0
booking_channel        0.0
payment_method         0.0
price_per_night_usd    0.0
total_price_usd        0.0
booking_status         0.0
guest_rating           0.0
special_requests       0.0
booking_month          0.0
nights_check           0.0
is_cancelled           0.0
calculated_total       0.0
ratio                  0.0
checkin_year           0.0
checkin_month          0.0
checkin_weekday        0.0
checkin_is_weekend     0.0
length_of_stay_days    0.0
is_domestic_booking    0.0
hotel_booking_count    0.0
city_booking_count     0.0
Date                   0.0
Year                   0.0
Month                  0.0
Month name             0.0
Day                    0.0
Day name               0.0
dtype: float64

In [110]:
df['guest_rating'] = df['guest_rating'].fillna(df['guest_rating'].mean())

In [111]:
df['special_requests'] = df['special_requests'].fillna('No Request')

In [112]:
print(df.isnull().sum())

Unnamed: 0             0
booking_id             0
hotel_id               0
hotel_name             0
city                   0
country                0
hotel_stars            0
room_type              0
guest_name             0
guest_email            0
adults                 0
children               0
checkin_date           0
checkout_date          0
nights                 0
booking_date           0
booking_channel        0
payment_method         0
price_per_night_usd    0
total_price_usd        0
booking_status         0
guest_rating           0
special_requests       0
booking_month          0
nights_check           0
is_cancelled           0
calculated_total       0
ratio                  0
checkin_year           0
checkin_month          0
checkin_weekday        0
checkin_is_weekend     0
length_of_stay_days    0
is_domestic_booking    0
hotel_booking_count    0
city_booking_count     0
Date                   0
Year                   0
Month                  0
Month name             0
Day                    0
Day name               0
dtype: int64

In [113]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           600000 non-null  int64
 1   booking_id           600000 non-null  int64
 2   hotel_id             600000 non-null  int64
 3   hotel_name           600000 non-null  str
 4   city                 600000 non-null  str
 5   country              600000 non-null  str
 6   hotel_stars          600000 non-null  int64
 7   room_type            600000 non-null  str
 8   guest_name           600000 non-null  str
 9   guest_email          600000 non-null  str
 10  adults               600000 non-null  int64
 11  children             600000 non-null  int64
 12  checkin_date         600000 non-null  str
 13  checkout_date        600000 non-null  str
 14  nights               600000 non-null  int64
 15  booking_date         600000 non-null  str
 16  booking_channel      600000 non-null  str
 17  payment_method       600000 non-null  str
 18  price_per_night_usd  600000 non-null  float64
 19  total_price_usd      600000 non-null  float64
 20  booking_status       600000 non-null  str
 21  guest_rating         600000 non-null  float64
 22  special_requests     600000 non-null  str
 23  booking_month        600000 non-null  str
 24  nights_check         600000 non-null  int64
 25  is_cancelled         600000 non-null  str
 26  calculated_total     600000 non-null  float64
 27  ratio                600000 non-null  float64
 28  checkin_year         600000 non-null  int64
 29  checkin_month        600000 non-null  int64
 30  checkin_weekday      600000 non-null  str
 31  checkin_is_weekend   600000 non-null  int64
 32  length_of_stay_days  600000 non-null  float64
 33  is_domestic_booking  600000 non-null  int64
 34  hotel_booking_count  600000 non-null  int64
 35  city_booking_count   600000 non-null  int64
 36  Date                 600000 non-null  str
 37  Year                 600000 non-null  int64
 38  Month                600000 non-null  int64
 39  Month name           600000 non-null  str
 40  Day                  600000 non-null  int64
 41  Day name             600000 non-null  str
dtypes: float64(6), int64(17), str(19)
memory usage: 192.3 MB

In [114]:
df['checkout_date'] = pd.to_datetime(df['checkout_date'])

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           600000 non-null  int64
 1   booking_id           600000 non-null  int64
 2   hotel_id             600000 non-null  int64
 3   hotel_name           600000 non-null  str
 4   city                 600000 non-null  str
 5   country              600000 non-null  str
 6   hotel_stars          600000 non-null  int64
 7   room_type            600000 non-null  str
 8   guest_name           600000 non-null  str
 9   guest_email          600000 non-null  str
 10  adults               600000 non-null  int64
 11  children             600000 non-null  int64
 12  checkin_date         600000 non-null  str
 13  checkout_date        600000 non-null  datetime64[us]
 14  nights               600000 non-null  int64
 15  booking_date         600000 non-null  str
 16  booking_channel      600000 non-null  str
 17  payment_method       600000 non-null  str
 18  price_per_night_usd  600000 non-null  float64
 19  total_price_usd      600000 non-null  float64
 20  booking_status       600000 non-null  str
 21  guest_rating         600000 non-null  float64
 22  special_requests     600000 non-null  str
 23  booking_month        600000 non-null  str
 24  nights_check         600000 non-null  int64
 25  is_cancelled         600000 non-null  str
 26  calculated_total     600000 non-null  float64
 27  ratio                600000 non-null  float64
 28  checkin_year         600000 non-null  int64
 29  checkin_month        600000 non-null  int64
 30  checkin_weekday      600000 non-null  str
 31  checkin_is_weekend   600000 non-null  int64
 32  length_of_stay_days  600000 non-null  float64
 33  is_domestic_booking  600000 non-null  int64
 34  hotel_booking_count  600000 non-null  int64
 35  city_booking_count   600000 non-null  int64
 36  Date                 600000 non-null  str
 37  Year                 600000 non-null  int64
 38  Month                600000 non-null  int64
 39  Month name           600000 non-null  str
 40  Day                  600000 non-null  int64
 41  Day name             600000 non-null  str
dtypes: datetime64[us](1), float64(6), int64(17), str(18)
memory usage: 192.3 MB

In [116]:
numeric_cols = ['adults', 'children', 'nights', 'price_per_night_usd', 'total_price_usd']

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = ((df[col] < lower_bound) | (df[col] > upper_bound)).sum()
    print(col, "outliers:", outliers)

adults outliers: 0
children outliers: 0
nights outliers: 0
price_per_night_usd outliers: 0
total_price_usd outliers: 0

In [117]:
numeric_cols = ['price_per_night_usd', 'total_price_usd']

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)

In [118]:
print(df[['price_per_night_usd', 'total_price_usd']].describe())

       price_per_night_usd  total_price_usd
count        600000.000000    600000.000000
mean            261.880537      1854.288842
std             117.038976      1324.682448
min              44.100000        39.340000
25%             171.630000       809.190000
50%             239.240000      1555.380000
75%             333.050000      2598.960000
max             575.180000      5283.615000

## 3- Data Preprocessing

In [119]:
df.head()

,Unnamed: 0,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,...,length_of_stay_days,is_domestic_booking,hotel_booking_count,city_booking_count,Date,Year,Month,Month name,Day,Day name
0,41,42,57,Ocean Boutique Hotel 57,Amsterdam,Netherlands,4,Double,Wei Yilmaz,wei.yilmaz42@hotmail.com,...,9.0,0,2439,26480,2024-01-22,2024,1,January,22,Monday
1,50,51,247,Sapphire Palace 247,Singapore,Singapore,4,Double,Maria Martinez,maria.martinez51@yahoo.com,...,9.0,0,2377,26191,2024-01-17,2024,1,January,17,Wednesday
2,173,174,138,Palm Suites 138,Cairo,Egypt,2,Double,Salma Bianchi,salma.bianchi174@hotmail.com,...,8.0,1,2439,9658,2024-01-03,2024,1,January,3,Wednesday
3,179,180,27,Grand Boutique Hotel 27,Paris,France,3,Twin,James Nassar,james.nassar180@hotmail.com,...,3.0,0,2416,21513,2024-01-23,2024,1,January,23,Tuesday
4,211,212,69,Royal Boutique Hotel 69,Sharm El Sheikh,Egypt,4,Single,Luca Kim,luca.kim212@gmail.com,...,1.0,1,2361,35839,2024-01-04,2024,1,January,4,Thursday

In [120]:
df.dtypes

Unnamed: 0                      int64
booking_id                      int64
hotel_id                        int64
hotel_name                        str
city                              str
country                           str
hotel_stars                     int64
room_type                         str
guest_name                        str
guest_email                       str
adults                          int64
children                        int64
checkin_date                      str
checkout_date          datetime64[us]
nights                          int64
booking_date                      str
booking_channel                   str
payment_method                    str
price_per_night_usd           float64
total_price_usd               float64
booking_status                    str
guest_rating                  float64
special_requests                  str
booking_month                     str
nights_check                    int64
is_cancelled                      str
calculated_total              float64
ratio                         float64
checkin_year                    int64
checkin_month                   int64
checkin_weekday                   str
checkin_is_weekend              int64
length_of_stay_days           float64
is_domestic_booking             int64
hotel_booking_count             int64
city_booking_count              int64
Date                              str
Year                            int64
Month                           int64
Month name                        str
Day                             int64
Day name                          str
dtype: object

In [121]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           600000 non-null  int64
 1   booking_id           600000 non-null  int64
 2   hotel_id             600000 non-null  int64
 3   hotel_name           600000 non-null  str
 4   city                 600000 non-null  str
 5   country              600000 non-null  str
 6   hotel_stars          600000 non-null  int64
 7   room_type            600000 non-null  str
 8   guest_name           600000 non-null  str
 9   guest_email          600000 non-null  str
 10  adults               600000 non-null  int64
 11  children             600000 non-null  int64
 12  checkin_date         600000 non-null  str
 13  checkout_date        600000 non-null  datetime64[us]
 14  nights               600000 non-null  int64
 15  booking_date         600000 non-null  str
 16  booking_channel      600000 non-null  str
 17  payment_method       600000 non-null  str
 18  price_per_night_usd  600000 non-null  float64
 19  total_price_usd      600000 non-null  float64
 20  booking_status       600000 non-null  str
 21  guest_rating         600000 non-null  float64
 22  special_requests     600000 non-null  str
 23  booking_month        600000 non-null  str
 24  nights_check         600000 non-null  int64
 25  is_cancelled         600000 non-null  str
 26  calculated_total     600000 non-null  float64
 27  ratio                600000 non-null  float64
 28  checkin_year         600000 non-null  int64
 29  checkin_month        600000 non-null  int64
 30  checkin_weekday      600000 non-null  str
 31  checkin_is_weekend   600000 non-null  int64
 32  length_of_stay_days  600000 non-null  float64
 33  is_domestic_booking  600000 non-null  int64
 34  hotel_booking_count  600000 non-null  int64
 35  city_booking_count   600000 non-null  int64
 36  Date                 600000 non-null  str
 37  Year                 600000 non-null  int64
 38  Month                600000 non-null  int64
 39  Month name           600000 non-null  str
 40  Day                  600000 non-null  int64
 41  Day name             600000 non-null  str
dtypes: datetime64[us](1), float64(6), int64(17), str(18)
memory usage: 192.3 MB

In [122]:
df['checkin_date'] = pd.to_datetime(df['checkin_date'])
df['booking_date'] = pd.to_datetime(df['booking_date'])
df['booking_month'] = df['booking_date'].dt.to_period('M')

In [123]:
df['booking_month'] = df['booking_month'].dt.to_timestamp()

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           600000 non-null  int64
 1   booking_id           600000 non-null  int64
 2   hotel_id             600000 non-null  int64
 3   hotel_name           600000 non-null  str
 4   city                 600000 non-null  str
 5   country              600000 non-null  str
 6   hotel_stars          600000 non-null  int64
 7   room_type            600000 non-null  str
 8   guest_name           600000 non-null  str
 9   guest_email          600000 non-null  str
 10  adults               600000 non-null  int64
 11  children             600000 non-null  int64
 12  checkin_date         600000 non-null  datetime64[us]
 13  checkout_date        600000 non-null  datetime64[us]
 14  nights               600000 non-null  int64
 15  booking_date         600000 non-null  datetime64[us]
 16  booking_channel      600000 non-null  str
 17  payment_method       600000 non-null  str
 18  price_per_night_usd  600000 non-null  float64
 19  total_price_usd      600000 non-null  float64
 20  booking_status       600000 non-null  str
 21  guest_rating         600000 non-null  float64
 22  special_requests     600000 non-null  str
 23  booking_month        600000 non-null  datetime64[us]
 24  nights_check         600000 non-null  int64
 25  is_cancelled         600000 non-null  str
 26  calculated_total     600000 non-null  float64
 27  ratio                600000 non-null  float64
 28  checkin_year         600000 non-null  int64
 29  checkin_month        600000 non-null  int64
 30  checkin_weekday      600000 non-null  str
 31  checkin_is_weekend   600000 non-null  int64
 32  length_of_stay_days  600000 non-null  float64
 33  is_domestic_booking  600000 non-null  int64
 34  hotel_booking_count  600000 non-null  int64
 35  city_booking_count   600000 non-null  int64
 36  Date                 600000 non-null  str
 37  Year                 600000 non-null  int64
 38  Month                600000 non-null  int64
 39  Month name           600000 non-null  str
 40  Day                  600000 non-null  int64
 41  Day name             600000 non-null  str
dtypes: datetime64[us](4), float64(6), int64(17), str(15)
memory usage: 192.3 MB

In [125]:
df['nights_check'] = (df['checkout_date'] - df['checkin_date']).dt.days
print(df[df['nights_check'] != df['nights']])

Empty DataFrame
Columns: [Unnamed: 0, booking_id, hotel_id, hotel_name, city, country, hotel_stars, room_type, guest_name, guest_email, adults, children, checkin_date, checkout_date, nights, booking_date, booking_channel, payment_method, price_per_night_usd, total_price_usd, booking_status, guest_rating, special_requests, booking_month, nights_check, is_cancelled, calculated_total, ratio, checkin_year, checkin_month, checkin_weekday, checkin_is_weekend, length_of_stay_days, is_domestic_booking, hotel_booking_count, city_booking_count, Date, Year, Month, Month name, Day, Day name]
Index: []

[0 rows x 42 columns]

In [126]:
print(df[df['total_price_usd'] <= 0])

Empty DataFrame
Columns: [Unnamed: 0, booking_id, hotel_id, hotel_name, city, country, hotel_stars, room_type, guest_name, guest_email, adults, children, checkin_date, checkout_date, nights, booking_date, booking_channel, payment_method, price_per_night_usd, total_price_usd, booking_status, guest_rating, special_requests, booking_month, nights_check, is_cancelled, calculated_total, ratio, checkin_year, checkin_month, checkin_weekday, checkin_is_weekend, length_of_stay_days, is_domestic_booking, hotel_booking_count, city_booking_count, Date, Year, Month, Month name, Day, Day name]
Index: []

[0 rows x 42 columns]

In [127]:
print(df[(df['adults'] + df['children']) == 0])

Empty DataFrame
Columns: [Unnamed: 0, booking_id, hotel_id, hotel_name, city, country, hotel_stars, room_type, guest_name, guest_email, adults, children, checkin_date, checkout_date, nights, booking_date, booking_channel, payment_method, price_per_night_usd, total_price_usd, booking_status, guest_rating, special_requests, booking_month, nights_check, is_cancelled, calculated_total, ratio, checkin_year, checkin_month, checkin_weekday, checkin_is_weekend, length_of_stay_days, is_domestic_booking, hotel_booking_count, city_booking_count, Date, Year, Month, Month name, Day, Day name]
Index: []

[0 rows x 42 columns]

In [128]:
print(df['city'].unique())
print(df['booking_channel'].unique())

<StringArray>
[      'Amsterdam',       'Singapore',           'Cairo',           'Paris',
 'Sharm El Sheikh',    'Kuala Lumpur',            'Rome',         'Bangkok',
     'Los Angeles',        'Istanbul',           'Luxor',            'Doha',
           'Dubai',           'Tokyo',       'Abu Dhabi',          'Vienna',
          'Jeddah',           'Amman',          'London',       'Barcelona',
          'Beirut',          'Berlin',          'Riyadh',        'New York',
         'Antalya',      'Casablanca',           'Tunis',          'Athens',
      'Alexandria',        'Hurghada']
Length: 30, dtype: str
<StringArray>
[         'Agoda',   'Travel Agent', 'Direct Website',        'Expedia',
    'Booking.com',        'Walk-in',        'Trivago',         'Airbnb']
Length: 8, dtype: str

In [129]:
df.duplicated().sum()

np.int64(0)

In [130]:
print(df['total_price_usd'].describe())

count    600000.000000
mean       1854.288842
std        1324.682448
min          39.340000
25%         809.190000
50%        1555.380000
75%        2598.960000
max        5283.615000
Name: total_price_usd, dtype: float64

In [131]:
result = []

for status in df['booking_status']:
    if status == 'Cancelled' or status == 'No-Show':
        result.append('Cancelled')
    else:
        result.append('Confirmed')

df['is_cancelled'] = result

In [132]:
print(df['is_cancelled'].value_counts())

is_cancelled
Confirmed    479767
Cancelled    120233
Name: count, dtype: int64

In [133]:
print(df['is_cancelled'].value_counts(normalize=True) * 100)

is_cancelled
Confirmed    79.961167
Cancelled    20.038833
Name: proportion, dtype: float64

In [134]:
df.head()

,Unnamed: 0,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,...,length_of_stay_days,is_domestic_booking,hotel_booking_count,city_booking_count,Date,Year,Month,Month name,Day,Day name
0,41,42,57,Ocean Boutique Hotel 57,Amsterdam,Netherlands,4,Double,Wei Yilmaz,wei.yilmaz42@hotmail.com,...,9.0,0,2439,26480,2024-01-22,2024,1,January,22,Monday
1,50,51,247,Sapphire Palace 247,Singapore,Singapore,4,Double,Maria Martinez,maria.martinez51@yahoo.com,...,9.0,0,2377,26191,2024-01-17,2024,1,January,17,Wednesday
2,173,174,138,Palm Suites 138,Cairo,Egypt,2,Double,Salma Bianchi,salma.bianchi174@hotmail.com,...,8.0,1,2439,9658,2024-01-03,2024,1,January,3,Wednesday
3,179,180,27,Grand Boutique Hotel 27,Paris,France,3,Twin,James Nassar,james.nassar180@hotmail.com,...,3.0,0,2416,21513,2024-01-23,2024,1,January,23,Tuesday
4,211,212,69,Royal Boutique Hotel 69,Sharm El Sheikh,Egypt,4,Single,Luca Kim,luca.kim212@gmail.com,...,1.0,1,2361,35839,2024-01-04,2024,1,January,4,Thursday

In [135]:
print(df[(df['guest_rating'] < 1) | (df['guest_rating'] > 5)])

Empty DataFrame
Columns: [Unnamed: 0, booking_id, hotel_id, hotel_name, city, country, hotel_stars, room_type, guest_name, guest_email, adults, children, checkin_date, checkout_date, nights, booking_date, booking_channel, payment_method, price_per_night_usd, total_price_usd, booking_status, guest_rating, special_requests, booking_month, nights_check, is_cancelled, calculated_total, ratio, checkin_year, checkin_month, checkin_weekday, checkin_is_weekend, length_of_stay_days, is_domestic_booking, hotel_booking_count, city_booking_count, Date, Year, Month, Month name, Day, Day name]
Index: []

[0 rows x 42 columns]

In [136]:
df['calculated_total'] = df['price_per_night_usd'] * df['nights']
df['ratio'] = df['total_price_usd'] / df['calculated_total']
print(df['ratio'].describe())

count    600000.000000
mean          0.953274
std           0.087608
min           0.656144
25%           0.931362
50%           1.000000
75%           1.000000
max           1.528774
Name: ratio, dtype: float64

### 4- Feature Engineering

In [137]:
print(df.shape)
df.head()

(600000, 42)

,Unnamed: 0,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,...,length_of_stay_days,is_domestic_booking,hotel_booking_count,city_booking_count,Date,Year,Month,Month name,Day,Day name
0,41,42,57,Ocean Boutique Hotel 57,Amsterdam,Netherlands,4,Double,Wei Yilmaz,wei.yilmaz42@hotmail.com,...,9.0,0,2439,26480,2024-01-22,2024,1,January,22,Monday
1,50,51,247,Sapphire Palace 247,Singapore,Singapore,4,Double,Maria Martinez,maria.martinez51@yahoo.com,...,9.0,0,2377,26191,2024-01-17,2024,1,January,17,Wednesday
2,173,174,138,Palm Suites 138,Cairo,Egypt,2,Double,Salma Bianchi,salma.bianchi174@hotmail.com,...,8.0,1,2439,9658,2024-01-03,2024,1,January,3,Wednesday
3,179,180,27,Grand Boutique Hotel 27,Paris,France,3,Twin,James Nassar,james.nassar180@hotmail.com,...,3.0,0,2416,21513,2024-01-23,2024,1,January,23,Tuesday
4,211,212,69,Royal Boutique Hotel 69,Sharm El Sheikh,Egypt,4,Single,Luca Kim,luca.kim212@gmail.com,...,1.0,1,2361,35839,2024-01-04,2024,1,January,4,Thursday

In [138]:
df['checkin_year'] = df['checkin_date'].dt.year
df['checkin_month'] = df['checkin_date'].dt.month
df['checkin_weekday'] = df['checkin_date'].dt.day_name()
df['checkin_is_weekend'] = df['checkin_date'].dt.dayofweek.isin([4, 5]).astype(int)

In [139]:
df['length_of_stay_days'] = (df['checkout_date'] - df['checkin_date']).dt.days
df.loc[df['length_of_stay_days'] < 0, 'length_of_stay_days'] = None

In [140]:
df[['checkin_date', 'checkout_date', 'length_of_stay_days', 'checkin_weekday']].head()

  checkin_date checkout_date  length_of_stay_days checkin_weekday
0   2024-01-22    2024-01-31                  9.0          Monday
1   2024-01-17    2024-01-26                  9.0       Wednesday
2   2024-01-03    2024-01-11                  8.0       Wednesday
3   2024-01-23    2024-01-26                  3.0         Tuesday
4   2024-01-04    2024-01-05                  1.0        Thursday

In [141]:
unique_country = df['country'].unique()
print(unique_country)

<StringArray>
[ 'Netherlands',    'Singapore',        'Egypt',       'France',
     'Malaysia',        'Italy',     'Thailand',          'USA',
       'Turkey',        'Qatar',          'UAE',        'Japan',
      'Austria', 'Saudi Arabia',       'Jordan',           'UK',
        'Spain',      'Lebanon',      'Germany',      'Morocco',
      'Tunisia',       'Greece']
Length: 22, dtype: str

In [142]:
df['is_domestic_booking'] = (df['country'] == 'Egypt').astype(int)
df['country'].value_counts()

country
Egypt           98571
UK              45408
USA             40705
Japan           38662
Saudi Arabia    36026
Turkey          31158
UAE             26619
Netherlands     26480
Singapore       26191
Thailand        26157
Jordan          24055
Malaysia        23951
Italy           23935
France          21513
Lebanon         19288
Tunisia         17057
Austria         16779
Qatar           16750
Spain           14332
Greece           9641
Germany          9506
Morocco          7216
Name: count, dtype: int64

In [143]:
df['hotel_booking_count'] = df.groupby('hotel_id')['booking_id'].transform('count')
df['city_booking_count'] = df.groupby('city')['booking_id'].transform('count')

In [144]:
df[['hotel_id', 'hotel_booking_count', 'city', 'city_booking_count']].head()

   hotel_id  hotel_booking_count             city  city_booking_count
0        57                 2439        Amsterdam               26480
1       247                 2377        Singapore               26191
2       138                 2439            Cairo                9658
3        27                 2416            Paris               21513
4        69                 2361  Sharm El Sheikh               35839

##### RFM Segmentation

In [145]:
df_backup = df.copy()

In [146]:
df['Date'] = df['checkin_date'].dt.date
df['Year'] = df['checkin_date'].dt.year
df['Month'] = df['checkin_date'].dt.month
df['Month name'] = df['checkin_date'].dt.month_name()
df['Day'] = df['checkin_date'].dt.day
df['Day name'] = df['checkin_date'].dt.day_name()

In [147]:
df = df.sort_values(["Year", "Month"])

In [148]:
analysis_date = df["checkin_date"].max() + pd.Timedelta(days=1)

RFM = df.groupby("guest_email").agg(
    r_recency=("checkin_date", lambda x: (analysis_date - x.max()).days),
    f_frequency=("booking_id", "nunique"),
    m_monetary=("total_price_usd", "sum")
).reset_index()

In [149]:
RFM

                               guest_email  r_recency  f_frequency  m_monetary
0       ahmed.abdelrahman11750@outlook.com         62            1      310.96
1        ahmed.abdelrahman121497@yahoo.com        433            1     1380.84
2       ahmed.abdelrahman122098@icloud.com        156            1     2930.64
3        ahmed.abdelrahman138467@gmail.com        914            1      403.41
4       ahmed.abdelrahman142586@icloud.com        209            1      251.36
...                                    ...        ...          ...         ...
599995       zeynep.youssef96204@gmail.com        273            1     2878.44
599996      zeynep.youssef97053@icloud.com         61            1     2896.66
599997      zeynep.youssef97528@icloud.com        224            1     2687.76
599998     zeynep.youssef97660@hotmail.com        500            1     2869.00
599999      zeynep.youssef98445@icloud.com        553            1     2315.60

[600000 rows x 4 columns]

In [150]:
RFM["R"] = pd.qcut(RFM["r_recency"].rank(method="first", ascending=False), 5, labels=[1, 2, 3, 4, 5]).astype(int)
RFM["F"] = pd.qcut(RFM["f_frequency"].rank(method="first"), 5, labels=[1, 2, 3, 4, 5]).astype(int)
RFM["M"] = pd.qcut(RFM["m_monetary"].rank(method="first"), 5, labels=[1, 2, 3, 4, 5]).astype(int)

In [151]:
RFM

,guest_email,r_recency,f_frequency,m_monetary,R,F,M
0,ahmed.abdelrahman11750@outlook.com,62,1,310.96,5,1,1
1,ahmed.abdelrahman121497@yahoo.com,433,1,1380.84,4,1,3
2,ahmed.abdelrahman122098@icloud.com,156,1,2930.64,5,1,5
3,ahmed.abdelrahman138467@gmail.com,914,1,403.41,1,1,1
4,ahmed.abdelrahman142586@icloud.com,209,1,251.36,5,1,1
...,...,...,...,...,...,...,...
599995,zeynep.youssef96204@gmail.com,273,1,2878.44,4,5,4
599996,zeynep.youssef97053@icloud.com,61,1,2896.66,5,5,4
599997,zeynep.youssef97528@icloud.com,224,1,2687.76,4,5,4
599998,zeynep.youssef97660@hotmail.com,500,1,2869.00,3,5,4
599999,zeynep.youssef98445@icloud.com,553,1,2315.60,3,5,4

In [152]:
RFM["RFM Score"] = (
    RFM['R'].astype(str) +
    RFM['F'].astype(str) +
    RFM['M'].astype(str)
).astype(int)

RFM

,guest_email,r_recency,f_frequency,m_monetary,R,F,M,RFM Score
0,ahmed.abdelrahman11750@outlook.com,62,1,310.96,5,1,1,511
1,ahmed.abdelrahman121497@yahoo.com,433,1,1380.84,4,1,3,413
2,ahmed.abdelrahman122098@icloud.com,156,1,2930.64,5,1,5,515
3,ahmed.abdelrahman138467@gmail.com,914,1,403.41,1,1,1,111
4,ahmed.abdelrahman142586@icloud.com,209,1,251.36,5,1,1,511
...,...,...,...,...,...,...,...,...
599995,zeynep.youssef96204@gmail.com,273,1,2878.44,4,5,4,454
599996,zeynep.youssef97053@icloud.com,61,1,2896.66,5,5,4,554
599997,zeynep.youssef97528@icloud.com,224,1,2687.76,4,5,4,454
599998,zeynep.youssef97660@hotmail.com,500,1,2869.00,3,5,4,354
599999,zeynep.youssef98445@icloud.com,553,1,2315.60,3,5,4,354

In [153]:
def segmantation(score):
    score = int(score)
    if score <= 155:
        return "bronze"
    elif score <= 255:
        return "silver"
    elif score <= 355:
        return "gold"
    elif score <= 455:
        return " prem"
    else:
        return "tait"

RFM["Customer segmantation"] = RFM["RFM Score"].apply(segmantation)

RFM

,guest_email,r_recency,f_frequency,m_monetary,R,F,M,RFM Score,Customer segmantation
0,ahmed.abdelrahman11750@outlook.com,62,1,310.96,5,1,1,511,tait
1,ahmed.abdelrahman121497@yahoo.com,433,1,1380.84,4,1,3,413,prem
2,ahmed.abdelrahman122098@icloud.com,156,1,2930.64,5,1,5,515,tait
3,ahmed.abdelrahman138467@gmail.com,914,1,403.41,1,1,1,111,bronze
4,ahmed.abdelrahman142586@icloud.com,209,1,251.36,5,1,1,511,tait
...,...,...,...,...,...,...,...,...,...
599995,zeynep.youssef96204@gmail.com,273,1,2878.44,4,5,4,454,prem
599996,zeynep.youssef97053@icloud.com,61,1,2896.66,5,5,4,554,tait
599997,zeynep.youssef97528@icloud.com,224,1,2687.76,4,5,4,454,prem
599998,zeynep.youssef97660@hotmail.com,500,1,2869.00,3,5,4,354,gold
599999,zeynep.youssef98445@icloud.com,553,1,2315.60,3,5,4,354,gold

In [154]:
RFM.to_csv("hotel_bookings_RFM.csv", index=False)

In [155]:
df.to_csv(r"C:\Users\hp\Downloads\hotel_bookings.csv")