## 1- Dataset & EDA

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\Hp\OneDrive - New Ismailia National University\Documents\NTI\hotel_bookings.csv")
df_backup=df.copy()

In [3]:
print(df.shape)

(600000, 22)

In [4]:
df.head()

,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,adults,...,checkout_date,nights,booking_date,booking_channel,payment_method,price_per_night_usd,total_price_usd,booking_status,guest_rating,special_requests
0,1,220,Continental Plaza 220,Tunis,Tunisia,2,Double,Chen Anderson,chen.anderson1@gmail.com,4,...,2024-03-06,6,2023-12-02,Booking.com,Debit Card,151.46,908.76,Confirmed,NaN,NaN
1,2,152,Pearl Suites 152,Riyadh,Saudi Arabia,2,Triple,Robert Demir,robert.demir2@icloud.com,1,...,2025-10-15,6,2025-09-26,Expedia,Credit Card,149.21,895.26,No-Show,NaN,NaN
2,3,86,Star Beach Resort 86,Kuala Lumpur,Malaysia,5,Executive Suite,Olivia Bianchi,olivia.bianchi3@hotmail.com,1,...,2026-11-09,7,2026-09-14,Expedia,Credit Card,645.43,4518.01,Confirmed,NaN,Quiet room
3,4,184,Ocean Palace 184,Bangkok,Thailand,4,Single,Giulia Kim,giulia.kim4@yahoo.com,4,...,2024-07-16,5,2024-06-29,Direct Website,Credit Card,156.95,707.80,Confirmed,NaN,Honeymoon setup
4,5,155,Pearl Boutique Hotel 155,London,UK,3,Executive Suite,Hassan Taylor,hassan.taylor5@outlook.com,4,...,2025-09-02,8,2025-07-17,Expedia,PayPal,374.13,2993.04,Confirmed,NaN,Honeymoon setup

In [5]:
df.tail()

,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,adults,...,checkout_date,nights,booking_date,booking_channel,payment_method,price_per_night_usd,total_price_usd,booking_status,guest_rating,special_requests
599995,599996,41,Imperial Suites 41,Luxor,Egypt,2,Double,Isabella Garcia,isabella.garcia599996@outlook.com,2,...,2025-10-01,14,2025-09-15,Travel Agent,Credit Card,124.68,1745.52,Confirmed,NaN,Baby crib
599996,599997,173,Palm Boutique Hotel 173,Tokyo,Japan,3,Double,Mona Ivanov,mona.ivanov599997@gmail.com,3,...,2025-09-07,11,2025-07-31,Airbnb,Debit Card,185.01,2035.11,Completed,2.0,NaN
599997,599998,37,Sapphire Residence 37,Beirut,Lebanon,2,Family Suite,Mahmoud Haddad,mahmoud.haddad599998@hotmail.com,3,...,2026-03-12,4,2026-03-02,Travel Agent,Credit Card,295.73,1182.92,Confirmed,NaN,NaN
599998,599999,108,Grand Residence 108,Los Angeles,USA,2,Twin,Ahmed Kim,ahmed.kim599999@gmail.com,2,...,2024-09-20,6,2024-08-07,Booking.com,Debit Card,183.33,1099.98,Completed,3.0,Late check-in
599999,600000,153,Paradise Towers 153,Tunis,Tunisia,2,Family Suite,Ali Taylor,ali.taylor600000@icloud.com,2,...,2026-07-10,3,2026-06-09,Expedia,Bank Transfer,204.60,613.80,Cancelled,NaN,Sea view room

In [6]:
print("Info about columns and data types:")
df.info()

Info about columns and data types:
<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   booking_id           600000 non-null  int64
 1   hotel_id             600000 non-null  int64
 2   hotel_name           600000 non-null  str
 3   city                 600000 non-null  str
 4   country              600000 non-null  str
 5   hotel_stars          600000 non-null  int64
 6   room_type            600000 non-null  str
 7   guest_name           600000 non-null  str
 8   guest_email          600000 non-null  str
 9   adults               600000 non-null  int64
 10  children             600000 non-null  int64
 11  checkin_date         600000 non-null  str
 12  checkout_date        600000 non-null  str
 13  nights               600000 non-null  int64
 14  booking_date         600000 non-null  str
 15  booking_channel      600000 non-null  str
 16  payment_method       600000 non-null  str
 17  price_per_night_usd  600000 non-null  float64
 18  total_price_usd      600000 non-null  float64
 19  booking_status       600000 non-null  str
 20  guest_rating         300067 non-null  float64
 21  special_requests     479696 non-null  str
dtypes: float64(3), int64(6), str(13)
memory usage: 100.7 MB

In [7]:
print("Statistics for numeric columns:")
print(df.describe())

Statistics for numeric columns:
          booking_id       hotel_id    hotel_stars         adults  \
count  600000.000000  600000.000000  600000.000000  600000.000000
mean   300000.500000     125.456407       3.462128       2.499810
std    173205.225094      72.141805       1.124806       1.119172
min         1.000000       1.000000       2.000000       1.000000
25%    150000.750000      63.000000       2.000000       1.000000
50%    300000.500000     126.000000       4.000000       2.000000
75%    450000.250000     188.000000       4.000000       4.000000
max    600000.000000     250.000000       5.000000       4.000000

            children         nights  price_per_night_usd  total_price_usd  \
count  600000.000000  600000.000000        600000.000000    600000.000000
mean        1.500790       7.501678           262.826602      1884.962756
std         1.118458       4.026189           119.918897      1421.114161
min         0.000000       1.000000            44.100000        39.340000
25%         1.000000       4.000000           171.630000       809.190000
50%         2.000000       7.000000           239.240000      1555.380000
75%         3.000000      11.000000           333.050000      2598.960000
max         3.000000      14.000000           879.320000     12259.800000

        guest_rating
count  300067.000000
mean        2.996807
std         1.415779
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000

In [8]:
print("Statistics for text/categorical columns:")
print(df.describe(include='object'))

Statistics for text/categorical columns:

C:\Users\Hp\AppData\Local\Temp\ipykernel_25632\2035940989.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))

                    hotel_name    city country room_type           guest_name  \
count                   600000  600000  600000    600000               600000
unique                     250      30      22         7                 1187
top     Sunset Beach Resort 61  London   Egypt    Triple  William Abdelrahman
freq                      2549   45408   98571     86138                 1485

                     guest_email checkin_date checkout_date booking_date  \
count                     600000       600000        600000       600000
unique                    600000         1095          1108         1184
top     chen.anderson1@gmail.com   2026-07-06    2025-04-29   2025-03-28
freq                           1          641           632          623

       booking_channel payment_method booking_status special_requests
count           600000         600000         600000           479696
unique               8              6              4               12
top        Booking.com    Credit Card      Completed  Honeymoon setup
freq            168119         252067         300067            40202

In [9]:
print("Missing values in each column:")
df.isnull().sum()

Missing values in each column:

booking_id                  0
hotel_id                    0
hotel_name                  0
city                        0
country                     0
hotel_stars                 0
room_type                   0
guest_name                  0
guest_email                 0
adults                      0
children                    0
checkin_date                0
checkout_date               0
nights                      0
booking_date                0
booking_channel             0
payment_method              0
price_per_night_usd         0
total_price_usd             0
booking_status              0
guest_rating           299933
special_requests       120304
dtype: int64

In [10]:
print("Number of duplicate rows:")
df.duplicated().sum()

Number of duplicate rows:

np.int64(0)

In [11]:
df['booking_date'] = pd.to_datetime(df['booking_date'])
df['checkin_date'] = pd.to_datetime(df['checkin_date'])

In [12]:
df['booking_month'] = df['booking_date'].dt.to_period('M')

In [13]:
avg_price_by_stars = df.groupby('hotel_stars')['total_price_usd'].mean()
print("\nAverage total price by hotel stars:")
print(avg_price_by_stars)

Average total price by hotel stars:
hotel_stars
2    1426.555669
3    1705.793965
4    2083.846470
5    2363.193671
Name: total_price_usd, dtype: float64

In [14]:
total_bookings = len(df)
print(total_bookings)

600000

In [15]:
status_percent = df['booking_status'].value_counts(normalize=True) * 100
print(status_percent)

booking_status
Completed    50.011167
Confirmed    29.950000
Cancelled    15.014333
No-Show       5.024500
Name: proportion, dtype: float64

In [16]:
avg_nights = df['nights'].mean()
print(f"Average nights per booking: {avg_nights:.2f}")

Average nights per booking: 7.50

In [17]:
avg_price = df['total_price_usd'].mean()
print(f"Average total price per booking: {avg_price:.2f} USD")

Average total price per booking: 1884.96 USD

In [18]:
most_common_room = df['room_type'].mode()[0]
print(f"Most common room type: {most_common_room}")

Most common room type: Triple

In [19]:
most_common_channel = df['booking_channel'].mode()[0]
print(f"Most common booking channel: {most_common_channel}")

Most common booking channel: Booking.com

## 2- Data Cleaning

In [20]:
print("Duplicate rows:", df.duplicated().sum())
print("Percentage:", round(df.duplicated().sum()/len(df)*100, 1))

Duplicate rows: 0
Percentage: 0.0

In [21]:
df.drop_duplicates(inplace=True)
print(df.shape)

(600000, 23)

In [22]:
print(df.isnull().sum())
print()
print(round(df.isnull().sum()/len(df)*100, 1))

booking_id                  0
hotel_id                    0
hotel_name                  0
city                        0
country                     0
hotel_stars                 0
room_type                   0
guest_name                  0
guest_email                 0
adults                      0
children                    0
checkin_date                0
checkout_date               0
nights                      0
booking_date                0
booking_channel             0
payment_method              0
price_per_night_usd         0
total_price_usd             0
booking_status              0
guest_rating           299933
special_requests       120304
booking_month               0
dtype: int64

booking_id              0.0
hotel_id                0.0
hotel_name              0.0
city                    0.0
country                 0.0
hotel_stars             0.0
room_type               0.0
guest_name              0.0
guest_email             0.0
adults                  0.0
children                0.0
checkin_date            0.0
checkout_date           0.0
nights                  0.0
booking_date            0.0
booking_channel         0.0
payment_method          0.0
price_per_night_usd     0.0
total_price_usd         0.0
booking_status          0.0
guest_rating           50.0
special_requests       20.1
booking_month           0.0
dtype: float64

In [23]:
df['guest_rating'] = df['guest_rating'].fillna(df['guest_rating'].mean())

In [24]:
df['special_requests'] = df['special_requests'].fillna('No Request')

In [25]:
print(df.isnull().sum())

booking_id             0
hotel_id               0
hotel_name             0
city                   0
country                0
hotel_stars            0
room_type              0
guest_name             0
guest_email            0
adults                 0
children               0
checkin_date           0
checkout_date          0
nights                 0
booking_date           0
booking_channel        0
payment_method         0
price_per_night_usd    0
total_price_usd        0
booking_status         0
guest_rating           0
special_requests       0
booking_month          0
dtype: int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 23 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   booking_id           600000 non-null  int64
 1   hotel_id             600000 non-null  int64
 2   hotel_name           600000 non-null  str
 3   city                 600000 non-null  str
 4   country              600000 non-null  str
 5   hotel_stars          600000 non-null  int64
 6   room_type            600000 non-null  str
 7   guest_name           600000 non-null  str
 8   guest_email          600000 non-null  str
 9   adults               600000 non-null  int64
 10  children             600000 non-null  int64
 11  checkin_date         600000 non-null  datetime64[us]
 12  checkout_date        600000 non-null  str
 13  nights               600000 non-null  int64
 14  booking_date         600000 non-null  datetime64[us]
 15  booking_channel      600000 non-null  str
 16  payment_method       600000 non-null  str
 17  price_per_night_usd  600000 non-null  float64
 18  total_price_usd      600000 non-null  float64
 19  booking_status       600000 non-null  str
 20  guest_rating         600000 non-null  float64
 21  special_requests     600000 non-null  str
 22  booking_month        600000 non-null  period[M]
dtypes: datetime64[us](2), float64(3), int64(6), period[M](1), str(11)
memory usage: 105.3 MB

In [27]:
df['checkout_date'] = pd.to_datetime(df['checkout_date'])

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 23 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   booking_id           600000 non-null  int64
 1   hotel_id             600000 non-null  int64
 2   hotel_name           600000 non-null  str
 3   city                 600000 non-null  str
 4   country              600000 non-null  str
 5   hotel_stars          600000 non-null  int64
 6   room_type            600000 non-null  str
 7   guest_name           600000 non-null  str
 8   guest_email          600000 non-null  str
 9   adults               600000 non-null  int64
 10  children             600000 non-null  int64
 11  checkin_date         600000 non-null  datetime64[us]
 12  checkout_date        600000 non-null  datetime64[us]
 13  nights               600000 non-null  int64
 14  booking_date         600000 non-null  datetime64[us]
 15  booking_channel      600000 non-null  str
 16  payment_method       600000 non-null  str
 17  price_per_night_usd  600000 non-null  float64
 18  total_price_usd      600000 non-null  float64
 19  booking_status       600000 non-null  str
 20  guest_rating         600000 non-null  float64
 21  special_requests     600000 non-null  str
 22  booking_month        600000 non-null  period[M]
dtypes: datetime64[us](3), float64(3), int64(6), period[M](1), str(10)
memory usage: 105.3 MB

In [29]:
numeric_cols = ['adults', 'children', 'nights', 'price_per_night_usd', 'total_price_usd']

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = ((df[col] < lower_bound) | (df[col] > upper_bound)).sum()
    print(col, "outliers:", outliers)

adults outliers: 0
children outliers: 0
nights outliers: 0
price_per_night_usd outliers: 10226
total_price_usd outliers: 18260

In [30]:
numeric_cols = ['price_per_night_usd', 'total_price_usd']

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)

In [31]:
print(df[['price_per_night_usd', 'total_price_usd']].describe())

       price_per_night_usd  total_price_usd
count        600000.000000    600000.000000
mean            261.880537      1854.288842
std             117.038976      1324.682448
min              44.100000        39.340000
25%             171.630000       809.190000
50%             239.240000      1555.380000
75%             333.050000      2598.960000
max             575.180000      5283.615000

## 3- Data Preprocessing

In [33]:
df.head()

,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,adults,...,nights,booking_date,booking_channel,payment_method,price_per_night_usd,total_price_usd,booking_status,guest_rating,special_requests,booking_month
0,1,220,Continental Plaza 220,Tunis,Tunisia,2,Double,Chen Anderson,chen.anderson1@gmail.com,4,...,6,2023-12-02,Booking.com,Debit Card,151.46,908.76,Confirmed,2.996807,No Request,2023-12
1,2,152,Pearl Suites 152,Riyadh,Saudi Arabia,2,Triple,Robert Demir,robert.demir2@icloud.com,1,...,6,2025-09-26,Expedia,Credit Card,149.21,895.26,No-Show,2.996807,No Request,2025-09
2,3,86,Star Beach Resort 86,Kuala Lumpur,Malaysia,5,Executive Suite,Olivia Bianchi,olivia.bianchi3@hotmail.com,1,...,7,2026-09-14,Expedia,Credit Card,575.18,4518.01,Confirmed,2.996807,Quiet room,2026-09
3,4,184,Ocean Palace 184,Bangkok,Thailand,4,Single,Giulia Kim,giulia.kim4@yahoo.com,4,...,5,2024-06-29,Direct Website,Credit Card,156.95,707.80,Confirmed,2.996807,Honeymoon setup,2024-06
4,5,155,Pearl Boutique Hotel 155,London,UK,3,Executive Suite,Hassan Taylor,hassan.taylor5@outlook.com,4,...,8,2025-07-17,Expedia,PayPal,374.13,2993.04,Confirmed,2.996807,Honeymoon setup,2025-07

In [34]:
df.dtypes

booking_id                      int64
hotel_id                        int64
hotel_name                        str
city                              str
country                           str
hotel_stars                     int64
room_type                         str
guest_name                        str
guest_email                       str
adults                          int64
children                        int64
checkin_date           datetime64[us]
checkout_date          datetime64[us]
nights                          int64
booking_date           datetime64[us]
booking_channel                   str
payment_method                    str
price_per_night_usd           float64
total_price_usd               float64
booking_status                    str
guest_rating                  float64
special_requests                  str
booking_month               period[M]
dtype: object

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 23 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   booking_id           600000 non-null  int64
 1   hotel_id             600000 non-null  int64
 2   hotel_name           600000 non-null  str
 3   city                 600000 non-null  str
 4   country              600000 non-null  str
 5   hotel_stars          600000 non-null  int64
 6   room_type            600000 non-null  str
 7   guest_name           600000 non-null  str
 8   guest_email          600000 non-null  str
 9   adults               600000 non-null  int64
 10  children             600000 non-null  int64
 11  checkin_date         600000 non-null  datetime64[us]
 12  checkout_date        600000 non-null  datetime64[us]
 13  nights               600000 non-null  int64
 14  booking_date         600000 non-null  datetime64[us]
 15  booking_channel      600000 non-null  str
 16  payment_method       600000 non-null  str
 17  price_per_night_usd  600000 non-null  float64
 18  total_price_usd      600000 non-null  float64
 19  booking_status       600000 non-null  str
 20  guest_rating         600000 non-null  float64
 21  special_requests     600000 non-null  str
 22  booking_month        600000 non-null  period[M]
dtypes: datetime64[us](3), float64(3), int64(6), period[M](1), str(10)
memory usage: 105.3 MB

In [36]:
df['checkin_date'] = pd.to_datetime(df['checkin_date'])
df['booking_date'] = pd.to_datetime(df['booking_date'])
df['booking_month'] = df['booking_date'].dt.to_period('M')

In [37]:
df['booking_month'] = df['booking_month'].dt.to_timestamp()

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 23 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   booking_id           600000 non-null  int64
 1   hotel_id             600000 non-null  int64
 2   hotel_name           600000 non-null  str
 3   city                 600000 non-null  str
 4   country              600000 non-null  str
 5   hotel_stars          600000 non-null  int64
 6   room_type            600000 non-null  str
 7   guest_name           600000 non-null  str
 8   guest_email          600000 non-null  str
 9   adults               600000 non-null  int64
 10  children             600000 non-null  int64
 11  checkin_date         600000 non-null  datetime64[us]
 12  checkout_date        600000 non-null  datetime64[us]
 13  nights               600000 non-null  int64
 14  booking_date         600000 non-null  datetime64[us]
 15  booking_channel      600000 non-null  str
 16  payment_method       600000 non-null  str
 17  price_per_night_usd  600000 non-null  float64
 18  total_price_usd      600000 non-null  float64
 19  booking_status       600000 non-null  str
 20  guest_rating         600000 non-null  float64
 21  special_requests     600000 non-null  str
 22  booking_month        600000 non-null  datetime64[us]
dtypes: datetime64[us](4), float64(3), int64(6), str(10)
memory usage: 105.3 MB

In [39]:
df['nights_check'] = (df['checkout_date'] - df['checkin_date']).dt.days
print(df[df['nights_check'] != df['nights']])

Empty DataFrame
Columns: [booking_id, hotel_id, hotel_name, city, country, hotel_stars, room_type, guest_name, guest_email, adults, children, checkin_date, checkout_date, nights, booking_date, booking_channel, payment_method, price_per_night_usd, total_price_usd, booking_status, guest_rating, special_requests, booking_month, nights_check]
Index: []

[0 rows x 24 columns]

In [40]:
print(df[df['total_price_usd'] <= 0])

Empty DataFrame
Columns: [booking_id, hotel_id, hotel_name, city, country, hotel_stars, room_type, guest_name, guest_email, adults, children, checkin_date, checkout_date, nights, booking_date, booking_channel, payment_method, price_per_night_usd, total_price_usd, booking_status, guest_rating, special_requests, booking_month, nights_check]
Index: []

[0 rows x 24 columns]

In [41]:
print(df[(df['adults'] + df['children']) == 0])

Empty DataFrame
Columns: [booking_id, hotel_id, hotel_name, city, country, hotel_stars, room_type, guest_name, guest_email, adults, children, checkin_date, checkout_date, nights, booking_date, booking_channel, payment_method, price_per_night_usd, total_price_usd, booking_status, guest_rating, special_requests, booking_month, nights_check]
Index: []

[0 rows x 24 columns]

In [42]:
print(df['city'].unique())
print(df['booking_channel'].unique())

<StringArray>
[          'Tunis',          'Riyadh',    'Kuala Lumpur',         'Bangkok',
          'London',        'New York',       'Barcelona',          'Vienna',
            'Rome',           'Tokyo',           'Luxor', 'Sharm El Sheikh',
     'Los Angeles',           'Amman',        'Hurghada',       'Singapore',
       'Amsterdam',           'Dubai',          'Berlin',          'Jeddah',
           'Paris',       'Abu Dhabi',          'Athens',         'Antalya',
            'Doha',          'Beirut',      'Casablanca',        'Istanbul',
      'Alexandria',           'Cairo']
Length: 30, dtype: str
<StringArray>
[   'Booking.com',        'Expedia', 'Direct Website',          'Agoda',
         'Airbnb',        'Trivago',   'Travel Agent',        'Walk-in']
Length: 8, dtype: str

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
print(df['total_price_usd'].describe())

count    600000.000000
mean       1854.288842
std        1324.682448
min          39.340000
25%         809.190000
50%        1555.380000
75%        2598.960000
max        5283.615000
Name: total_price_usd, dtype: float64

In [45]:
result = []

for status in df['booking_status']:
    if status == 'Cancelled' or status == 'No-Show':
        result.append('Cancelled')
    else:
        result.append('Confirmed')

df['is_cancelled'] = result

In [46]:
print(df['is_cancelled'].value_counts())

is_cancelled
Confirmed    479767
Cancelled    120233
Name: count, dtype: int64

In [47]:
print(df['is_cancelled'].value_counts(normalize=True) * 100)

is_cancelled
Confirmed    79.961167
Cancelled    20.038833
Name: proportion, dtype: float64

In [48]:
df.head()

,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,adults,...,booking_channel,payment_method,price_per_night_usd,total_price_usd,booking_status,guest_rating,special_requests,booking_month,nights_check,is_cancelled
0,1,220,Continental Plaza 220,Tunis,Tunisia,2,Double,Chen Anderson,chen.anderson1@gmail.com,4,...,Booking.com,Debit Card,151.46,908.76,Confirmed,2.996807,No Request,2023-12-01,6,Confirmed
1,2,152,Pearl Suites 152,Riyadh,Saudi Arabia,2,Triple,Robert Demir,robert.demir2@icloud.com,1,...,Expedia,Credit Card,149.21,895.26,No-Show,2.996807,No Request,2025-09-01,6,Cancelled
2,3,86,Star Beach Resort 86,Kuala Lumpur,Malaysia,5,Executive Suite,Olivia Bianchi,olivia.bianchi3@hotmail.com,1,...,Expedia,Credit Card,575.18,4518.01,Confirmed,2.996807,Quiet room,2026-09-01,7,Confirmed
3,4,184,Ocean Palace 184,Bangkok,Thailand,4,Single,Giulia Kim,giulia.kim4@yahoo.com,4,...,Direct Website,Credit Card,156.95,707.80,Confirmed,2.996807,Honeymoon setup,2024-06-01,5,Confirmed
4,5,155,Pearl Boutique Hotel 155,London,UK,3,Executive Suite,Hassan Taylor,hassan.taylor5@outlook.com,4,...,Expedia,PayPal,374.13,2993.04,Confirmed,2.996807,Honeymoon setup,2025-07-01,8,Confirmed

In [49]:
print(df[(df['guest_rating'] < 1) | (df['guest_rating'] > 5)])

Empty DataFrame
Columns: [booking_id, hotel_id, hotel_name, city, country, hotel_stars, room_type, guest_name, guest_email, adults, children, checkin_date, checkout_date, nights, booking_date, booking_channel, payment_method, price_per_night_usd, total_price_usd, booking_status, guest_rating, special_requests, booking_month, nights_check, is_cancelled]
Index: []

[0 rows x 25 columns]

In [50]:
df['calculated_total'] = df['price_per_night_usd'] * df['nights']
df['ratio'] = df['total_price_usd'] / df['calculated_total']
print(df['ratio'].describe())

count    600000.000000
mean          0.953274
std           0.087608
min           0.656144
25%           0.931362
50%           1.000000
75%           1.000000
max           1.528774
Name: ratio, dtype: float64

### 4- Feature Engineering

In [51]:
print(df.shape)
df.head()

(600000, 27)

,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,adults,...,price_per_night_usd,total_price_usd,booking_status,guest_rating,special_requests,booking_month,nights_check,is_cancelled,calculated_total,ratio
0,1,220,Continental Plaza 220,Tunis,Tunisia,2,Double,Chen Anderson,chen.anderson1@gmail.com,4,...,151.46,908.76,Confirmed,2.996807,No Request,2023-12-01,6,Confirmed,908.76,1.000000
1,2,152,Pearl Suites 152,Riyadh,Saudi Arabia,2,Triple,Robert Demir,robert.demir2@icloud.com,1,...,149.21,895.26,No-Show,2.996807,No Request,2025-09-01,6,Cancelled,895.26,1.000000
2,3,86,Star Beach Resort 86,Kuala Lumpur,Malaysia,5,Executive Suite,Olivia Bianchi,olivia.bianchi3@hotmail.com,1,...,575.18,4518.01,Confirmed,2.996807,Quiet room,2026-09-01,7,Confirmed,4026.26,1.122136
3,4,184,Ocean Palace 184,Bangkok,Thailand,4,Single,Giulia Kim,giulia.kim4@yahoo.com,4,...,156.95,707.80,Confirmed,2.996807,Honeymoon setup,2024-06-01,5,Confirmed,784.75,0.901943
4,5,155,Pearl Boutique Hotel 155,London,UK,3,Executive Suite,Hassan Taylor,hassan.taylor5@outlook.com,4,...,374.13,2993.04,Confirmed,2.996807,Honeymoon setup,2025-07-01,8,Confirmed,2993.04,1.000000

In [52]:
df['checkin_year'] = df['checkin_date'].dt.year
df['checkin_month'] = df['checkin_date'].dt.month
df['checkin_weekday'] = df['checkin_date'].dt.day_name()
df['checkin_is_weekend'] = df['checkin_date'].dt.dayofweek.isin([4, 5]).astype(int)

In [53]:
df['length_of_stay_days'] = (df['checkout_date'] - df['checkin_date']).dt.days
df.loc[df['length_of_stay_days'] < 0, 'length_of_stay_days'] = None

In [54]:
df[['checkin_date', 'checkout_date', 'length_of_stay_days', 'checkin_weekday']].head()

  checkin_date checkout_date  length_of_stay_days checkin_weekday
0   2024-02-29    2024-03-06                  6.0        Thursday
1   2025-10-09    2025-10-15                  6.0        Thursday
2   2026-11-02    2026-11-09                  7.0          Monday
3   2024-07-11    2024-07-16                  5.0        Thursday
4   2025-08-25    2025-09-02                  8.0          Monday

In [55]:
unique_country = df['country'].unique()
print(unique_country)

<StringArray>
[     'Tunisia', 'Saudi Arabia',     'Malaysia',     'Thailand',
           'UK',          'USA',        'Spain',      'Austria',
        'Italy',        'Japan',        'Egypt',       'Jordan',
    'Singapore',  'Netherlands',          'UAE',      'Germany',
       'France',       'Greece',       'Turkey',        'Qatar',
      'Lebanon',      'Morocco']
Length: 22, dtype: str

In [56]:
df['is_domestic_booking'] = (df['country'] == 'Egypt').astype(int)
df['country'].value_counts()

country
Egypt           98571
UK              45408
USA             40705
Japan           38662
Saudi Arabia    36026
Turkey          31158
UAE             26619
Netherlands     26480
Singapore       26191
Thailand        26157
Jordan          24055
Malaysia        23951
Italy           23935
France          21513
Lebanon         19288
Tunisia         17057
Austria         16779
Qatar           16750
Spain           14332
Greece           9641
Germany          9506
Morocco          7216
Name: count, dtype: int64

In [57]:
df['hotel_booking_count'] = df.groupby('hotel_id')['booking_id'].transform('count')
df['city_booking_count'] = df.groupby('city')['booking_id'].transform('count')

In [58]:
df[['hotel_id', 'hotel_booking_count', 'city', 'city_booking_count']].head()

   hotel_id  hotel_booking_count          city  city_booking_count
0       220                 2364         Tunis               17057
1       152                 2402        Riyadh               16830
2        86                 2459  Kuala Lumpur               23951
3       184                 2417       Bangkok               26157
4       155                 2387        London               45408

In [59]:
df.head()

,booking_id,hotel_id,hotel_name,city,country,hotel_stars,room_type,guest_name,guest_email,adults,...,calculated_total,ratio,checkin_year,checkin_month,checkin_weekday,checkin_is_weekend,length_of_stay_days,is_domestic_booking,hotel_booking_count,city_booking_count
0,1,220,Continental Plaza 220,Tunis,Tunisia,2,Double,Chen Anderson,chen.anderson1@gmail.com,4,...,908.76,1.000000,2024,2,Thursday,0,6.0,0,2364,17057
1,2,152,Pearl Suites 152,Riyadh,Saudi Arabia,2,Triple,Robert Demir,robert.demir2@icloud.com,1,...,895.26,1.000000,2025,10,Thursday,0,6.0,0,2402,16830
2,3,86,Star Beach Resort 86,Kuala Lumpur,Malaysia,5,Executive Suite,Olivia Bianchi,olivia.bianchi3@hotmail.com,1,...,4026.26,1.122136,2026,11,Monday,0,7.0,0,2459,23951
3,4,184,Ocean Palace 184,Bangkok,Thailand,4,Single,Giulia Kim,giulia.kim4@yahoo.com,4,...,784.75,0.901943,2024,7,Thursday,0,5.0,0,2417,26157
4,5,155,Pearl Boutique Hotel 155,London,UK,3,Executive Suite,Hassan Taylor,hassan.taylor5@outlook.com,4,...,2993.04,1.000000,2025,8,Monday,0,8.0,0,2387,45408

##### RFM Segmentation

In [60]:
df_backup = df.copy()

In [62]:
df['Date'] = df['checkin_date'].dt.date
df['Year'] = df['checkin_date'].dt.year
df['Month'] = df['checkin_date'].dt.month
df['Month name'] = df['checkin_date'].dt.month_name()
df['Day'] = df['checkin_date'].dt.day
df['Day name'] = df['checkin_date'].dt.day_name()

In [63]:
df = df.sort_values(["Year", "Month"])

In [65]:
analysis_date = df["checkin_date"].max() + pd.Timedelta(days=1)

RFM = df.groupby("guest_email").agg(
    r_recency=("checkin_date", lambda x: (analysis_date - x.max()).days),
    f_frequency=("booking_id", "nunique"),
    m_monetary=("total_price_usd", "sum")
).reset_index()

In [66]:
RFM

                               guest_email  r_recency  f_frequency  m_monetary
0       ahmed.abdelrahman11750@outlook.com         62            1      310.96
1        ahmed.abdelrahman121497@yahoo.com        433            1     1380.84
2       ahmed.abdelrahman122098@icloud.com        156            1     2930.64
3        ahmed.abdelrahman138467@gmail.com        914            1      403.41
4       ahmed.abdelrahman142586@icloud.com        209            1      251.36
...                                    ...        ...          ...         ...
599995       zeynep.youssef96204@gmail.com        273            1     2878.44
599996      zeynep.youssef97053@icloud.com         61            1     2896.66
599997      zeynep.youssef97528@icloud.com        224            1     2687.76
599998     zeynep.youssef97660@hotmail.com        500            1     2869.00
599999      zeynep.youssef98445@icloud.com        553            1     2315.60

[600000 rows x 4 columns]

In [67]:
RFM["R"] = pd.qcut(RFM["r_recency"].rank(method="first", ascending=False), 5, labels=[1, 2, 3, 4, 5]).astype(int)
RFM["F"] = pd.qcut(RFM["f_frequency"].rank(method="first"), 5, labels=[1, 2, 3, 4, 5]).astype(int)
RFM["M"] = pd.qcut(RFM["m_monetary"].rank(method="first"), 5, labels=[1, 2, 3, 4, 5]).astype(int)

In [68]:
RFM

,guest_email,r_recency,f_frequency,m_monetary,R,F,M
0,ahmed.abdelrahman11750@outlook.com,62,1,310.96,5,1,1
1,ahmed.abdelrahman121497@yahoo.com,433,1,1380.84,4,1,3
2,ahmed.abdelrahman122098@icloud.com,156,1,2930.64,5,1,5
3,ahmed.abdelrahman138467@gmail.com,914,1,403.41,1,1,1
4,ahmed.abdelrahman142586@icloud.com,209,1,251.36,5,1,1
...,...,...,...,...,...,...,...
599995,zeynep.youssef96204@gmail.com,273,1,2878.44,4,5,4
599996,zeynep.youssef97053@icloud.com,61,1,2896.66,5,5,4
599997,zeynep.youssef97528@icloud.com,224,1,2687.76,4,5,4
599998,zeynep.youssef97660@hotmail.com,500,1,2869.00,3,5,4
599999,zeynep.youssef98445@icloud.com,553,1,2315.60,3,5,4

In [69]:
RFM["RFM Score"] = (
    RFM['R'].astype(str) +
    RFM['F'].astype(str) +
    RFM['M'].astype(str)
).astype(int)

RFM

,guest_email,r_recency,f_frequency,m_monetary,R,F,M,RFM Score
0,ahmed.abdelrahman11750@outlook.com,62,1,310.96,5,1,1,511
1,ahmed.abdelrahman121497@yahoo.com,433,1,1380.84,4,1,3,413
2,ahmed.abdelrahman122098@icloud.com,156,1,2930.64,5,1,5,515
3,ahmed.abdelrahman138467@gmail.com,914,1,403.41,1,1,1,111
4,ahmed.abdelrahman142586@icloud.com,209,1,251.36,5,1,1,511
...,...,...,...,...,...,...,...,...
599995,zeynep.youssef96204@gmail.com,273,1,2878.44,4,5,4,454
599996,zeynep.youssef97053@icloud.com,61,1,2896.66,5,5,4,554
599997,zeynep.youssef97528@icloud.com,224,1,2687.76,4,5,4,454
599998,zeynep.youssef97660@hotmail.com,500,1,2869.00,3,5,4,354
599999,zeynep.youssef98445@icloud.com,553,1,2315.60,3,5,4,354

In [70]:
def segmantation(score):
    score = int(score)
    if score <= 155:
        return "bronze"
    elif score <= 255:
        return "silver"
    elif score <= 355:
        return "gold"
    elif score <= 455:
        return " prem"
    else:
        return "tait"

RFM["Customer segmantation"] = RFM["RFM Score"].apply(segmantation)

RFM

,guest_email,r_recency,f_frequency,m_monetary,R,F,M,RFM Score,Customer segmantation
0,ahmed.abdelrahman11750@outlook.com,62,1,310.96,5,1,1,511,tait
1,ahmed.abdelrahman121497@yahoo.com,433,1,1380.84,4,1,3,413,prem
2,ahmed.abdelrahman122098@icloud.com,156,1,2930.64,5,1,5,515,tait
3,ahmed.abdelrahman138467@gmail.com,914,1,403.41,1,1,1,111,bronze
4,ahmed.abdelrahman142586@icloud.com,209,1,251.36,5,1,1,511,tait
...,...,...,...,...,...,...,...,...,...
599995,zeynep.youssef96204@gmail.com,273,1,2878.44,4,5,4,454,prem
599996,zeynep.youssef97053@icloud.com,61,1,2896.66,5,5,4,554,tait
599997,zeynep.youssef97528@icloud.com,224,1,2687.76,4,5,4,454,prem
599998,zeynep.youssef97660@hotmail.com,500,1,2869.00,3,5,4,354,gold
599999,zeynep.youssef98445@icloud.com,553,1,2315.60,3,5,4,354,gold

In [71]:
RFM.to_csv("hotel_bookings_RFM.csv", index=False)

In [72]:
df.to_csv(r"C:\Users\Hp\OneDrive - New Ismailia National University\Documents\NTI\New_hotel_bookings.csv")